apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
  namespace: sre-dashboard
spec:
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
    spec:
      containers:
        - name: news-service
          image: news-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: news-service
  namespace: sre-dashboard
spec:
  selector:
    app: news-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
